server:
  port: ${APP_PORT}

spring:
  application:
    name: demo

  flyway:
    locations: classpath:/db/migration
    schemas: employees
    baselineOnMigrate: true
    enabled: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URI}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

  secutity:
    jwt-secret: ${JWT_SECRET}